package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.25

import (
	"airbnb-property-be/graph/model"
	"context"
	"fmt"
)

// PropertyTypes is the resolver for the propertyTypes field.
func (r *queryResolver) PropertyTypes(ctx context.Context, limit *int, page *int) (*model.PropertyTypes, error) {
	r.Property.GetPropertyTypes(ctx, limit, page)
	panic(fmt.Errorf("not implemented: PropertyTypes - propertyTypes"))
}
