// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Pagination struct {
	Limit    *int `json:"limit"`
	Page     *int `json:"page"`
	PageSize *int `json:"pageSize"`
}

type PropertyType struct {
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	Link      *string   `json:"link"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type PropertyTypes struct {
	Data []*PropertyType `json:"data"`
	Meta *Pagination     `json:"meta"`
}
