stage:
origins:
domain:
mock:
  otp:
creds:
  privatekey:
  publiccert:
httpserver:
  host:
  port:
db:
  user:
  password:
  name:
  host:
  port:
  sslmode:
  timezone:
cache:
  auth:
    host:
    password:
    db:
  otp:
    host:
    password:
    db:
jwt:
  # example using https://generate-secret.now.sh/32
  secret:
kafka:
  clientid:
  brokers:
  version:
  consumer:
    group:
    assigner:
    isuseoldest:
    router:
      separator:
aws:
  region:
  accesskey:
  secretkey:
  url:
  bucket:
    name:
elastic:
  addresses:
  username:
  password:
  separator: